
storage:
    directory: "records"
    max_files: 1
    max_file_size: 100000000 # 100MB approx.
    pattern: "liveweb-%(seq)s-%(timestamp)s.arc.gz"

extra_headers:
  Connection: "keep-alive"


user_agent: "ia_archiver(OS-Wayback)"

# Max size of ARC record that can be stored in cache
max_cacheable_size: "10MB"

#redis_params:
#    host: localhost
#    port: 6379
#    db: 0

# Maximum amount of time for a URL to be downloaded
timeout: 1
  
#http_passthrough: True

#cache:
#    type: redis

# Extra headers which will be sent by the proxy to the remote site.
